#
# Standard Jekyll Configuration
#
exclude: [CNAME, Gemfile, Gemfile.lock, Rakefile, README.md, site.scss, bin, vendor]
markdown: redcarpet
permalink: /:categories/:title.html
port: 9393
pygments: true
rdiscount:
  extensions: [smart]

#
# Site Configuration
#
domain: dab.io
title: Danilo Braband

#
# Configuration for Enhancements
#
gauges:
  data-site-id: 507bc980613f5d27a6000002
